name: CI (master)

on:
  push:
    branches: [master, main, actions-test]
  pull_request:
    branches: [master, main]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node_version:
          - current
          - lts/*

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
        if: runner.os == 'Windows'
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build package
        run: yarn build
      - name: Run tests
        run: yarn test:ci
        env:
          NODE_OPTIONS: --enable-source-maps
